### PR TITLE
Chinese Translation Added.

### PR DESCRIPTION
**Pull request by BaiTian6641**
Almost done.
Working on the contents of Floppy disks.

Fixes #

## Proposed Changes
Added Chinese translation for this mod.
  -
  -
  -

### CODE REVIEW

**Review by LtxProgrammer — APPROVED** [review]
Approved

**Review by LtxProgrammer — CHANGES_REQUESTED** [review]
Revoke approve; request mentions needing to translate floppies

**Comment by BaiTian6641** [comment]
ok

**Comment by BaiTian6641** [comment]
Finished Translation.

**Pull request merged**
