### PR TITLE
Update InfuserMenu.java

### PR DESCRIPTION
**Pull request by Foxyas**
# Fixed? 
Maybe Fixed The Latex Flask Recipe

## Changes
  ```stack.is(Items.GLASS_BOTTLE)``` to ```stack.is(ChangedItems.getBlockItem(ChangedBlocks.ERLENMEYER_FLASK.get())```

### CODE REVIEW

**Comment by Foxyas** [comment]
image
I'm assuming it's a oops

**Comment by Foxyas** [comment]
also you should upload that like a Hotfix

**Comment by bijimio** [comment]
I noticed this issue too, I kept wondering why JEI didn't show a recipe for the latex flasks

**Comment by Foxyas** [comment]
> I noticed this issue too, I kept wondering why JEI didn't show a recipe for the latex flasks

Yeah and btw would be a good addition if the jei plugin Show What Item you would need put in the Slot of the Right for craft that type of Item [Like the flask and Arrow]

**Comment by LtxProgrammer** [comment]
I suspect this is from when I originally wrote the code to use potion bottles, before switching it to flasks.

**Review by LtxProgrammer — APPROVED** [review]

**Pull request merged**
